% This file updates MIL test harness model executes with test cases.
%Inputs:  Harnessmodel generated by SLDV
%Outputs: Testcases in MAT file format
%         Updated Test Harness model
%         Model coverage report(HTML).
         
function [ret]=MIL_Testing(Model_Name,mdl_type,MFile_name)
try

         
	bdclose all
	
	evalin('base', MFile_name);
	hpath = strcat(pwd,'\sldv_output\',Model_Name);
    if(mdl_type=='1') %pass .mdl
        hname = strcat(hpath,'\',Model_Name,'_harness.mdl');
		disp('Get model type is mdl')	
    else
        hname = strcat(hpath,'\',Model_Name,'_harness.slx'); 
		disp('Get model type is slx')    
    end
	%BCM_C1A_EcuMonitor_Constant_2;
	%SAMPLE_TIME;
    [SUCCESS,MESSAGE,MESSAGEID] = movefile(hname,pwd,'f');	
    disp(hname);
	disp('success_0');
	
    if(SUCCESS == 1)
    
           disp('success_1');
        model_name=strcat(Model_Name,'_harness');
        disp('success_2');
        %apply config settings
        apply_config_setting(model_name,'config');
        
        %%1
        harness_name = MIL_Test_Updation(model_name); %This will return the MIL test harness model name
        %%2
        MIL_Test_Execution(harness_name); %pass the MIL test harness name for test execution

        disp('MIL testing completed successfully')
        ret = 0;
        exit(0);
    else
        disp('Error While execution of MIL Testing')
        ret = 1;
        exit(1);        
    end
catch
    disp('Error While execution of MIL Testing')
    ret = 1;
	exit(1);
end
end

