% This file updates SIL test harness model executes with test cases.
%Inputs:  Harnessmodel generated by SLDV
%Outputs: Testcases in MAT file format
%         Updated SIL Test Harness model
%         Model coverage report(HTML).
         
function [ret]=SIL_Testing(Model_Name,MFile_name,file_path)
try
         
	bdclose all
    
    
	evalin('base', MFile_name);
	model_name=strcat(Model_Name,'_harness');
    
	harness_name = SIL_Test_Updation(model_name); %This will return the SIL test harness model name
	
	SIL_Test_Execution(harness_name); %pass the SIL test harness name for test execution

	disp('SIL testing completed successfully')	
    ret = 0;
	exit(0);
catch e
    disp('Error While execution of SIL Testing')
	fid = fopen(file_path, 'w');
    fprintf(fid,'%s\n',e.message);     
    fclose(fid);
    ret = 1;
	exit(1);
end
end